// docs/src/pages/marketplace.tsx
import React, { useState, useEffect } from "react";
import Layout from "@theme/Layout";
import styles from "./marketplace.module.css";

interface Plugin {
  name: string;
  title: string;
  description: string;
  file: string;
  url?: string;
}

const REGISTRY_URL =
  "https://raw.githubusercontent.com/floatpane/matcha/master/plugins/registry.json";
const RAW_BASE =
  "https://raw.githubusercontent.com/floatpane/matcha/master/plugins/";

function pluginUrl(plugin: Plugin): string {
  return plugin.url || `${RAW_BASE}${plugin.file}`;
}

function installCmd(plugin: Plugin): string {
  return `matcha install ${pluginUrl(plugin)}`;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      className={styles.copyButton}
      onClick={handleCopy}
      title="Copy to clipboard"
      type="button"
    >
      {copied ? "Copied!" : "Copy"}
    </button>
  );
}

function PluginCard({ plugin }: { plugin: Plugin }) {
  const cmd = installCmd(plugin);

  return (
    <div className={styles.card}>
      <h3 className={styles.cardTitle}>{plugin.title}</h3>
      <p className={styles.cardDescription}>{plugin.description}</p>
      <div className={styles.installLabel}>Install:</div>
      <div className={styles.installRow}>
        <code className={styles.installCommand}>{cmd}</code>
        <CopyButton text={cmd} />
      </div>
    </div>
  );
}

export default function Marketplace(): React.JSX.Element {
  const [plugins, setPlugins] = useState<Plugin[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(REGISTRY_URL)
      .then((res) => {
        if (!res.ok)
          throw new Error(`Failed to fetch registry (${res.status})`);
        return res.json();
      })
      .then((data: Plugin[]) => {
        setPlugins(data);
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message);
        setLoading(false);
      });
  }, []);

  return (
    <Layout
      title="Plugin Marketplace"
      description="Browse and install Matcha plugins"
    >
      <div className={styles.marketplace}>
        <div className={styles.header}>
          <h1>Plugin Marketplace</h1>
          <p>
            Browse community plugins for Matcha. Click install commands to copy.
          </p>
        </div>
        {loading && <p className={styles.count}>Loading plugins...</p>}
        {error && <p className={styles.error}>Error: {error}</p>}
        {!loading && !error && (
          <>
            <p className={styles.count}>{plugins.length} plugins available</p>
            <div className={styles.grid}>
              {plugins.map((plugin) => (
                <PluginCard key={plugin.name} plugin={plugin} />
              ))}
            </div>
          </>
        )}
      </div>
    </Layout>
  );
}

// docs/components/marketplace.vue
<template>
  <div class="marketplace">
    <div v-if="loading" class="loading">Loading plugins...</div>
    <div v-if="error" class="error">Error: {{ error }}</div>
    <div v-if="!loading && !error" class="grid">
      <PluginCard v-for="plugin in plugins" :key="plugin.name" :plugin="plugin" />
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import PluginCard from "./PluginCard.vue";

const REGISTRY_URL =
  "https://raw.githubusercontent.com/floatpane/matcha/master/plugins/registry.json";

const plugins = ref([]);
const loading = ref(true);
const error = ref(null);

onMounted(() => {
  fetch(REGISTRY_URL)
    .then((res) => {
      if (!res.ok) throw new Error(`Failed to fetch registry (${res.status})`);
      return res.json();
    })
    .then((data) => {
      plugins.value = data;
      loading.value = false;
    })
    .catch((err) => {
      error.value = err.message;
      loading.value = false;
    });
});
</script>

<style scoped>
.marketplace {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem 3rem;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
  gap: 1.25rem;
}

.loading,
.error {
  text-align: center;
  color: var(--muted);
  padding: 3rem 0;
  font-size: 1.1rem;
}

.error {
  color: var(--danger);
}
</style>
